### PR TITLE
fix(builder): Fix `BlockSchema` handling & type propagation

### LINKED ISSUE #7601: [Builder] Fix `BlockSchema` usage & type propagation
Current issues:

* JSON object schemas have a recursive structure; `BlockSchema.properties` is typed as `any`
* `CustomNodeData` has two slightly different definitions. One of them has `inputSchema: ObjectSchema`, the other has `inputSchema: BlockSchema`. Casting is done within ReactFlow, causing it to go unchecked by TypeScript.
* `ObjectSchema` definition is incomplete'
* Not all cases of possible [combined schemas](https://json-schema.org/understanding-json-schema/reference/combining) are handled in the node input field renderer

### PR DESCRIPTION
**Pull request by Pwuts**
- Resolves #7601

This issue was slowing me down significantly so I bumped its priority.

### Changes 🏗️
- Merge `Flow.tsx:CustomNodeData` type definition into `CustomNode.tsx:CustomNodeData`
- Move `lib/types:BlockSchema` type definition into `lib/autogpt-server-api/types` in place of `ObjectSchema`
- Expand and rename `BlockSchema` -> `BlockIOSchema` + `BlockIORootSchema`
- Fix all `BlockIOSchema` related type narrowing checks
- Add warning messages to fallback cases in `NodeInputField` logic

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

### CODE REVIEW

File: rnd/autogpt_builder/src/components/CustomNode.tsx [hunk 1]
```diff
@@ -4,23 +4,25 @@ import 'reactflow/dist/style.css';
...
-type CustomNodeData = {
+export type CustomNodeData = {
   blockType: string;
   title: string;
-  inputSchema: BlockSchema;
-  outputSchema: BlockSchema;
+  inputSchema: BlockIORootSchema;
+  outputSchema: BlockIORootSchema;
   hardcodedValues: { [key: string]: any };
   setHardcodedValues: (values: { [key: string]: any }) => void;
```
Comment (kcze) [inline rnd/autogpt_builder/src/components/CustomNode.tsx:23]: > `setHardcodedValues: (values: { [key: string]: any }) => void;`

I somehow don't like this because you need to pass function for each but I did the same with `setErrors` for validation and don't have idea how to do it well.

**Review by kcze — APPROVED** [review]
