### PR TITLE
fix(marketplace): Fix store card style

### LINKED ISSUE #8966: Marketplace - Reduce this margin here so that it's 12px
### Describe your issue.

Reduce this margin here so that it's 12px

image

### LINKED ISSUE #9221: Marketplace - responsive behavior on Agent cards, keep the element height the same
### Describe your issue.

When the window resizes, please keep the height of all of components in the card (the thumbnail image, title, author, description) the same. 

Currently when I resize the window, the title will collapse and create a new line. Please do the following:
1. Keep the same number of lines for all text elements (2 lines for the title, 1 line for author, 3 lines for description). Anything more than that, truncate the text
2. Keep the aspect ratio of the image the same when resizing the window. Don't change the aspect ratio no matter what. 

This is a GIF of the current behavior:
Clipboard-20250108-121433-100

Please take a look at the Apple App store for desired resizing behavior.
App Store - 1

### LINKED ISSUE #9222: Marketplace agent cards - Standardize card heights so it doesn't look like a camel's back (going up and down)
### Describe your issue.

We have a problem with our card heights being inconsistent in our Marketplace. This is not good design, our cards look like a camel's hump.. Let's standardize this.

Currently our character limit on the Agent name is too long, it results in inconsistent **card heights that are too tall** like this: 
Screenshot 2025-01-08 at 13 28 46

Can we try the following solution:
1. Limit the character count of the Agent title name to 40 characters. My goal is to limit the title to maximum 2 lines of text 
2. Anything more than that, we should truncate the title

------

We also run into this problem of **the cards being too short** like this: 
Screenshot 2025-01-08 at 13 35 47

Let's try the following solution: 
1. Align the thumbnail, author name, description to the top of the div 
2. Align the runs and the ratings to the bottom of the div
Screenshot 2025-01-08 at 13 45 04

### PR DESCRIPTION
**Pull request by Abhi1992002**
- fix #9222 
- fix #9221 
- fix #8966

### Changes made
- Standardized the height of store cards.
- Corrected spacing and responsiveness behavior.
- Removed horizontal margin and max-width from the featured section.
- Fixed the aspect ratio of the agent image in the store card.
- Now, a normal desktop screen displays 3 columns of agents instead of 4.

Screenshot 2025-04-07 at 7 09 40 AM

### CODE REVIEW

**Review by kcze — APPROVED** [review]
LGTM

File: autogpt_platform/frontend/src/components/agptui/StoreCard.tsx [hunk 1]
```diff
@@ -72,37 +72,46 @@ export const StoreCard: React.FC<StoreCardProps> = ({
...
-      {/* Content Section */}
-      <div className="w-full px-2 py-4">
-        {/* Title and Creator */}
-        <h3 className="mb-0.5 font-poppins text-2xl font-semibold text-[#272727] dark:text-neutral-100">
-          {agentName}
-        </h3>
-        {!hideAvatar && creatorName && (
-          <p className="mb-2.5 font-sans text-xl font-normal text-neutral-600 dark:text-neutral-400">
-            by {creatorName}
+      <div className="mt-[12px] flex w-full flex-1 flex-col px-4">
```
Comment (kcze) [inline autogpt_platform/frontend/src/components/agptui/StoreCard.tsx]:
```suggestion
      <div className="mt-3 flex w-full flex-1 flex-col px-4">
```
Better to not use pixels

Comment (Abhi1992002) [reply autogpt_platform/frontend/src/components/agptui/StoreCard.tsx]: Done..!!

File: autogpt_platform/frontend/src/components/agptui/StoreCard.tsx [hunk 2]
```diff
@@ -32,7 +32,7 @@ export const StoreCard: React.FC<StoreCardProps> = ({
 
   return (
     <div
-      className="inline-flex w-full max-w-[434px] cursor-pointer flex-col items-start justify-start gap-2.5 rounded-[26px] bg-white transition-all duration-300 hover:shadow-lg dark:bg-transparent dark:hover:shadow-gray-700"
+      className="flex h-[433px] w-full max-w-[434px] cursor-pointer flex-col items-start rounded-[26px] bg-white transition-all duration-300 hover:shadow-lg dark:bg-transparent dark:hover:shadow-gray-700"
```
Comment (majdyz) [inline autogpt_platform/frontend/src/components/agptui/StoreCard.tsx]: This height 433px max-width 434px is oddly specific is this expected ?

**Review by majdyz — APPROVED** [review]

**Comment by majdyz** [comment]
@Abhi1992002 Let me know if you have resolved the conflict so I can reapprove, but I'd recommend checking the hard-coded height & width too, can we tolerate it with multiple of 4 sizes so that we can use rem? or much much better: h-md & max-w-md (448px). 

Also rounded if can be tolerated to rounded-3xl.

**Comment by ntindle** [comment]
Can I get full-page screenshot + video of scrolling for this for @ograce1421 to approve?

File: autogpt_platform/frontend/src/components/agptui/StoreCard.tsx (hunk 2 above)
Comment (Abhi1992002) [reply autogpt_platform/frontend/src/components/agptui/StoreCard.tsx]: replaced height with 27 rem and max width with "md" (28 rem)

**Comment by Abhi1992002** [comment]
The height and width in this design are not exactly as per the original design. There’s a difference of about 10 to 15 px because I used rem and specific Tailwind utility classes. If you want it to match the design exactly, I can do that. I’ve also attached a video for reference.

@ograce1421 

https://github.com/user-attachments/assets/6cf5ea4c-b023-4f7e-a357-e12285d8ad31

**Review by Bentlybro — APPROVED** [review]
